language: ruby
cache: bundler
sudo: false
rvm:
- 2.3.1
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake db:schema:load
- bundle exec rake
env: RACK_ENV=test
