language: ruby
cache: bundler
sudo: false
rvm:
- 2.3.1
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake db:schema:load
- bundle exec rake
env: RACK_ENV=test
deploy:
  provider: rubygems
  api_key:
    secure: WLrcuYKYf0k34MkGPI4DtJ9XABnng5ANJ2t2eNTzgCczOlhvfbFzloGKoam8TxZprp061uz4liF4QNLpqavgRS9tY3iUGMGeZYYnx41ftto8rGrfJyL+nO27uWA/KU07GVBlr0V1p8rCiyUDpijzyp3FJDaUdpSZczAwaJlesTe0ZVN8BDksRbZz3OSJAOmLdX/MS6VRfuCUdyMN963edfg3sZST1LjvlxELdgr3uNNRFg1+n8Z05HRG7Jib8f2Rx91+QfErpE6sMzgmQ93gfFnx8Q74wS5E2SIJwiYX5TZeGgZbnzPIi1AtGgxm984pc60+CN/X/Kg5RW9q+wiHE6p8KNnbA0FkZveKr/fHtiA6sUqPj3L8jx6qKSp5scNQL/y43ey5no8EDozFNAstYM/COdNbYEbYvhnZA9dBKDG27Bmh+KhqVgqVT3JxDSku9R+yR9rahUeyZFKcGHaLDltlLfrbnIdueQ2SYBeDUD00Pg/FlQeXzBc1wTq2ldZJr34rWEr27KqZ/NMBIj/687Kuv5VvGoR9srifu0jy5FKaf/I7mr/O2q2R/++YNsUccYQvW3ENTVpyJqaGcDnpDd70C0N2ZZPwjcGhvl2z0jW4cSNAmEqDE1zh+uJVZnDxqYUVgb63odQ7IhsvzKZLbMNeyZqon+ACiFu2iIvHi1s=
  gem: mumuki-bibliotheca
  on:
    tags: true
    repo: mumuki/mumuki-bibliotheca-api
