language: ruby
cache: bundler
sudo: false
rvm:
- 2.0.0
script:
- bundle exec rspec
services:
- mongodb
env: RACK_ENV=test
addons:
  code_climate:
    repo_token: fc99046bbbd5bab2e17c7ce37e57a8ed9d04b79fce6d0d8904fb983bccb009e2
after_success: wget https://raw.githubusercontent.com/mumuki/mumuki-escualo/master/travis_deploy
  && chmod u+x travis_deploy && ./travis_deploy bibliotheca bibliotheca.mumuki.io
before_install:
- openssl aes-256-cbc -K $encrypted_d15a3399a687_key -iv $encrypted_d15a3399a687_iv
  -in escualo_rsa.enc -out escualo_rsa -d
