#!/bin/bash
set -e

echo ''
echo '__________._____.   .__  .__        __  .__                          '
echo '\______   \__\_ |__ |  | |__| _____/  |_|  |__   ____   ____ _____   '
echo ' |    |  _/  || __ \|  | |  |/  _ \   __\  |  \_/ __ \_/ ___\\__  \  '
echo ' |    |   \  || \_\ \  |_|  (  <_> )  | |   Y  \  ___/\  \___ / __ \_'
echo ' |______  /__||___  /____/__|\____/|__| |___|  /\___  >\___  >____  /'
echo '        \/        \/                         \/     \/     \/     \/ '
echo ''


echo "[MumukiDevstart::Bibliotheca] Installing dependencies...."
bundle install --quiet

echo "[MumukiDevstart::Bibliotheca] Preparing database...."
MUMUKI_BIBLIOTHECA_API_URL=http://bibliotheca-api.mumuki.io \
MUMUKI_THESAURUS_URL=http://thesaurus.mumuki.io bundle \
  exec rake db:drop db:create db:schema:load db:seed
