default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  mongo:
    host: localhost
    port: 27017
    database: bibliotheca

test:
  <<: *default
  database: db/test.sqlite3
  mongo:
    host: <%=ENV['MONGO_PORT_27017_TCP_ADDR'] || 'localhost' %>
    port: <%=ENV['MONGO_PORT_27017_TCP_PORT'] || 27017 %>
    database: bibliotheca-test
