common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: mumuki
  password: mumuki

development:
  <<: *common
  database: mumuki_development
  pool: 5
  timeout: 5000
  mongo:
    host: localhost
    port: 27017
    database: bibliotheca

test:
  <<: *common
  database: mumuki_test
  pool: 5
  timeout: 5000
  mongo:
    host: localhost
    port: 27017
    database: bibliotheca-test
