production:
  host: <%=ENV['OPENSHIFT_MONGODB_DB_HOST'] || ENV['MUMUKI_MONGODB_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_MONGODB_DB_PORT'] || ENV['MUMUKI_MONGODB_DB_PORT']%>
  user: <%=ENV['OPENSHIFT_MONGODB_DB_USERNAME'] || ENV['MUMUKI_MONGODB_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MONGODB_DB_PASSWORD'] || ENV['MUMUKI_MONGODB_DB_PASSWORD']%>
  database: <%=ENV['OPENSHIFT_APP_NAME'] || ENV['MUMUKI_APP_NAME']%>

development:
  host: localhost
  port: 27017
  database: bibliotheca

test:
  host: <%=ENV['MONGO_PORT_27017_TCP_ADDR']%>
  port: <%=ENV['MONGO_PORT_27017_TCP_PORT']%>
  database: bibliotheca-test
